guard 'shell' do
  watch('caesar_cipher_encrypt.rb') do |m|
    system("ruby  caesar_cipher_encrypt.rb")
  end

  watch('stock_picker.rb') do |m|
    system("ruby stock_picker_playground.rb")
  end
end
