#!/bin/bash
URI='/foo'
BODY=''
CLIENT_ID='public-api-key'
CLIENT_SECRET='secret-token'

SIGNATURE=$(./hmac.py $CLIENT_SECRET "$URI$BODY")

curl -i -H "Authorization: $CLIENT_ID:$SIGNATURE" "http://localhost:4567$URI"
